version: "3.9"
services:
  suma:
    build: ./suma
    ports:
      - "8001:8000"
    networks:
      - shape-net

  resta:
    build: ./resta
    ports:
      - "8002:8000"
    networks:
      - shape-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservicios
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shape-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  ecuacion:
    build: ./ecuacion
    ports:
      - "8003:8000"
    networks:
      - shape-net
    depends_on:
      mysql:
        condition: service_healthy
      suma:
        condition: service_started
      resta:
        condition: service_started

networks:
  shape-net:
    driver: bridge

volumes:
  mysql_data:
