apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecuacion
  namespace: microservicios
spec:
  selector:
    matchLabels:
      app: ecuacion
  template:
    metadata:
      labels:
        app: ecuacion
    spec:
      containers:
      - name: ecuacion
        image: ecuacion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ecuacion
  namespace: microservicios
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: ecuacion