apiVersion: apps/v1
kind: Deployment
metadata:
  name: suma
  namespace: microservicios
spec:
  selector:
    matchLabels:
      app: suma
  template:
    metadata:
      labels:
        app: suma
    spec:
      containers:
      - name: suma
        image: suma:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: suma
  namespace: microservicios
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: suma